### PR TITLE
`Coref`: Vectorize `get_predicted_antecedents`

### PR DESCRIPTION
**Pull request by shadeMe**
Ekes out a small performance improvement in the current training regime but should scale better with larger inputs.

### CODE REVIEW

**Comment by shadeMe** [comment]
Reverting this to draft to perform a few more tests.

**Comment by shadeMe** [comment]
Further testing revealed improvements of 7-8% during inference.

**Review by polm — APPROVED** [review]
Thanks, this looks good! :rocket:

**Comment by polm** [comment]
Unfortunately, while this works on Linux, it looks like the changes here cause an error on Windows. Stack trace:

```
spacy_experimental\coref\tests\test_coref.py:245:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\env\lib\site-packages\spacy\language.py:1025: in __call__
    error_handler(name, proc, [doc], e)
..\env\lib\site-packages\spacy\util.py:1658: in raise_error
    raise e
..\env\lib\site-packages\spacy\language.py:1020: in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
spacy\pipeline\trainable_pipe.pyx:56: in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
    ???
..\env\lib\site-packages\spacy\util.py:1658: in raise_error
    raise e
spacy\pipeline\trainable_pipe.pyx:52: in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
    ???
spacy_experimental\coref\coref_component.py:159: in predict
    predicted = get_predicted_clusters(xp, starts, ends, ant_idxs, scores)
spacy_experimental\coref\coref_util.py:116: in get_predicted_clusters
    get_predicted_antecedents(xp, antecedent_idx, antecedent_scores)
spacy_experimental\coref\coref_util.py:88: in get_predicted_antecedents
    xp.place(
<__array_function__ internals>:180: in place
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

arr = array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1])
mask = array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False]), vals = array([ 2, 10], dtype=int64)

    @array_function_dispatch(_place_dispatcher)
    def place(arr, mask, vals):
        """
        Change elements of an array based on conditional and input values.

        Similar to ``np.copyto(arr, vals, where=mask)``, the difference is that
        `place` uses the first N elements of `vals`, where N is the number of
        True values in `mask`, while `copyto` uses the elements where `mask`
        is True.

        Note that `extract` does the exact opposite of `place`.


        Parameters
        ----------
        arr : ndarray
            Array to put data into.
        mask : array_like
            Boolean mask array. Must have the same size as `a`.
        vals : 1-D sequence
            Values to put into `a`. Only the first N elements are used, where
            N is the number of True values in `mask`. If `vals` is smaller
            than N, it will be repeated, and if elements of `a` are to be masked,
            this sequence must be non-empty.

        See Also
        --------
        copyto, put, take, extract

        Examples
        --------
        >>> arr = np.arange(6).reshape(2, 3)
        >>> np.place(arr, arr>2, [44, 55])
        >>> arr
        array([[ 0,  1,  2],
               [44, 55, 44]])

        """
        if not isinstance(arr, np.ndarray):
            raise TypeError("argument 1 must be numpy.ndarray, "
                            "not {name}".format(name=type(arr).__name__))

>       return _insert(arr, mask, vals)
E       TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

(The docstring is actually included like that.) 

I guess the issue is not passing the `dtype` when calling `xp.full`? Could this also be resulting in truncation of values on Linux?

**Comment by shadeMe** [comment]
Huh! That's rather strange :thinking: What happens when you use the following, as per your suggestion?
```
out = xp.full(antecedent_idx.shape[0], -1,dtype=antecedent_idx.dtype)
```
Does the test pass?

**Comment by shadeMe** [comment]
Seems like the difference is behaviour has to do with the backend in play (`numpy` on Windows and `cupy` on Linux). Can you confirm this (you can just print out the string repr of `xp`)?

**Comment by polm** [comment]
Hm, that's really weird. For the record, setting `dtype` like I thought would fix it doesn't seem to change anything. In the tests, besides the one I added six others are failing too - it looks like it's anything that calls this function.

I'll need to follow up on this tomorrow, but let me know if there's anything I can check about my Windows configuration that might cause this. 

It also failed the Windows tests in the projects repo PR (https://github.com/explosion/projects/pull/101), so I'm pretty sure this isn't just my setup, but it might be sensitive to something in the environment.

**Pull request merged**
